{% set version = "3.0.0" %}

package:
  name: opt-einsum
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/o/opt_einsum/opt_einsum-{{ version }}.tar.gz
  sha256: 1f4f29678267ce941be30bb5e5adaa591df1084cedde80e86e2e3f3cffa8778f

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy >=1.7

test:
  imports:
    - opt_einsum
    - opt_einsum.backends
    - opt_einsum.tests

about:
  home: https://github.com/dgasmith/opt_einsum
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Optimizing numpys einsum function"

extra:
  recipe-maintainers:
    - ocefpaf
