travis:
  secure:
    BINSTAR_TOKEN: SjgqMNAkOt7yUPsSFNGxBYFkGA8GGRSy6CQZ0vRq6QstZ40nHZzMYKRHW+HwPPRnXpBAtXo9RHyAFtc+sDeiA539bJm/MP+cRphykduKacfED0oZOI3iuH+PhCJfTi1gr/Zo0vxvLSa8PWwPgvZ2kd/lLFBNMepEcjqsLF0Ym8rZ7CJbGWoCBWC4ZfACdHAq8TknQGGHjBdUFTa418hUoKfz0rqTOe+IfzUtSPd0reFOFcqeuvGCblma5lvG3qiZ1tTaFvLyexBTqvjirQmAu+6eyOaA9FjAPwGJ65jcIl/g9hk54+h0J5evNVM9Htxm24bqPth9op4k3TKTCtb057qVNY0F/G8Mp1plNINIWclYxU3cRYrANiCFtWGUAx+6FqfxfQV+B7f6tTYTX6eWkRElhitN2Bi/pgMSiMY/uvN2IGiK2Ev+GI+gHWrt6R9JSliESSmj1b91zZk4CDjjyPu7LH9XrixYfKL811X4Qu122lpzTLhlZzTyy6JWh/gnsfCtEDSS4X4zHY88mzQnE8kDX8iPEdVnRDcquCr+qMn8rW63iw8TX4kcDK696f+oM3G8X418DdvwdqzCOhmaMuPOJJTzR16B20t7M5GwyfGEFcyxAigXcBc+6IetSqHwxVAgI+73XPZFDXgdbtKFR6cv+IgGoC5ViQUrIwXEvYI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
